import React from 'react';
import { useCurrentFrame, useVideoConfig, AbsoluteFill, Img, Audio, Sequence, staticFile } from 'remotion';
import { COLORS } from '../../brand';
import { FONT_DISPLAY, FONT_BODY } from '../../fonts';
import CircularTimer from './CircularTimer';
import BreathingPhasePanel from './BreathingPhasePanel';
import PranayamCard from './PranayamCard';
import RestCard from './RestCard';
import NextRestPreview from './NextRestPreview';
import BreathAffirmationCard from './BreathAffirmationCard';
import SessionOverviewCard from './SessionOverviewCard';
import SparkleParticlesOverlay from '../brand/SparkleParticlesOverlay';
import PromoEndCard from '../brand/PromoEndCard';
import PeriodicLikeBanner, { likeBannerOpacity } from '../brand/PeriodicLikeBanner';
import TechniqueCompleteCard from './TechniqueCompleteCard';
import {
  PranayamType, PRANAYAM_SPECS, cycleSeconds, roundSeconds, totalReps, resolveBreath, repsPerRound,
} from './breathPattern';
import {
  INTRO_SEC, REST_SEC, VOICE_WINDOW_SEC, PROMO_SEC, CELEBRATE_SEC,
  T_BHASTRIKA, T_CELEB_1, T_REST_1, T_KAPALBHATI, T_CELEB_2, T_REST_2,
  T_ANULOM, T_CELEB_3, T_REST_3, T_BAHYA, T_CELEB_4, T_REST_4,
  T_BHRAMARI, T_FINALE, T_PROMO, SESSION_SEC,
} from './sessionTimeline';

// The master timeline lives in sessionTimeline.ts (plain TS) so the chapter list and
// the subtitle file can be generated from the same numbers this composition uses.

/**
 * Congratulation flash after each technique. Counts and units come straight from the
 * specs, so they can never drift from what the viewer actually just did.
 */
/** One round of breathing audio per technique, generated by gen_pranayam_sfx.py. */
const BREATH_TRACKS: Record<PranayamType, string> = {
  bhastrika: 'library/audio/pranayam/bhastrika_round.mp3',
  kapalbhati: 'library/audio/pranayam/kapalbhati_round.mp3',
  anulom_vilom: 'library/audio/pranayam/anulom_round.mp3',
  bahya: 'library/audio/pranayam/bahya_round.mp3',
  bhramari: 'library/audio/pranayam/bhramari_round.mp3',
};

const CELEBRATIONS: Array<{ at: number; type: PranayamType; index: number; title: string; isFinal?: boolean }> = [
  { at: T_CELEB_1, type: 'bhastrika', index: 1, title: 'Bellows Breathing' },
  { at: T_CELEB_2, type: 'kapalbhati', index: 2, title: 'Skull Shining Breath' },
  { at: T_CELEB_3, type: 'anulom_vilom', index: 3, title: 'Alternate Nostril Breathing' },
  { at: T_CELEB_4, type: 'bahya', index: 4, title: 'External Breath Retention' },
  { at: T_FINALE, type: 'bhramari', index: 5, title: 'Humming Bee Breath', isFinal: true },
];

export const compositionConfig = {
  id: 'Daily5Pranayam',
  width: 1920,
  height: 1080,
  fps: 30,
  durationInSeconds: SESSION_SEC,
};

export const Daily5Pranayam: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const currentTime = frame / fps;

  const isIntro       = currentTime < INTRO_SEC;
  const isBhastrika   = currentTime >= T_BHASTRIKA  && currentTime < T_CELEB_1;
  const isRest1       = currentTime >= T_REST_1     && currentTime < T_KAPALBHATI;
  const isKapalbhati  = currentTime >= T_KAPALBHATI && currentTime < T_CELEB_2;
  const isRest2       = currentTime >= T_REST_2     && currentTime < T_ANULOM;
  const isAnulomVilom = currentTime >= T_ANULOM     && currentTime < T_CELEB_3;
  const isRest3       = currentTime >= T_REST_3     && currentTime < T_BAHYA;
  const isBahya       = currentTime >= T_BAHYA      && currentTime < T_CELEB_4;
  const isRest4       = currentTime >= T_REST_4     && currentTime < T_BHRAMARI;
  const isBhramari    = currentTime >= T_BHRAMARI   && currentTime < T_FINALE;
  const isEndPromo    = currentTime >= T_PROMO;

  let currentType: PranayamType = 'bhastrika';
  if (isKapalbhati) currentType = 'kapalbhati';
  else if (isAnulomVilom) currentType = 'anulom_vilom';
  else if (isBahya) currentType = 'bahya';
  else if (isBhramari) currentType = 'bhramari';

  const isResting = isRest1 || isRest2 || isRest3 || isRest4;
  const isActiveTechnique = isBhastrika || isKapalbhati || isAnulomVilom || isBahya || isBhramari;

  // Time left in the whole session — reaches 00:00 when the last technique ends,
  // not when the promo ends.
  const sessionLeftSec = Math.max(0, Math.ceil(T_FINALE - currentTime));
  const sessionTimeLeft = `${String(Math.floor(sessionLeftSec / 60)).padStart(2, '0')}:${String(sessionLeftSec % 60).padStart(2, '0')}`;
  const sessionProgress = Math.min(1, Math.max(0, currentTime / T_FINALE));
  const bannerOpacity = isIntro ? 0 : likeBannerOpacity(currentTime, T_FINALE);

  const currentStartSec = isKapalbhati ? T_KAPALBHATI
    : isAnulomVilom ? T_ANULOM
    : isBahya ? T_BAHYA
    : isBhramari ? T_BHRAMARI
    : T_BHASTRIKA;

  // Live breath state for STROKE + ROUND badges above the timer
  const breathState = isActiveTechnique
    ? resolveBreath(PRANAYAM_SPECS[currentType], currentTime - currentStartSec)
    : null;

  return (
    <AbsoluteFill style={{ backgroundColor: '#f5ebe0', overflow: 'hidden' }}>
      {/* End Promotional Slides */}
      {isEndPromo && <PromoEndCard startSec={T_PROMO} />}
      {/* Congratulation flash + chime at the end of each technique. */}
      {CELEBRATIONS.map((c) => {
        if (currentTime < c.at || currentTime >= c.at + CELEBRATE_SEC) return null;
        const spec = PRANAYAM_SPECS[c.type];
        return (
          <React.Fragment key={c.type}>
            <Sequence from={Math.round(c.at * fps)} durationInFrames={Math.round(CELEBRATE_SEC * fps)}>
              <Audio src={staticFile('library/audio/pranayam/completion_chime.mp3')} volume={0.65} />
            </Sequence>
            <TechniqueCompleteCard
              startSec={c.at}
              durationSec={CELEBRATE_SEC}
              index={c.index}
              total={CELEBRATIONS.length}
              title={c.title}
              count={totalReps(spec)}
              unit={`${spec.repUnit}S`}
              isFinal={c.isFinal}
            />
          </React.Fragment>
        );
      })}
      {/* Periodic Like & Subscribe Overlay */}
      {!isEndPromo && !isIntro && <PeriodicLikeBanner until={T_PROMO} />}
      {/* Soft Background Meditation Music */}
      <Audio src={staticFile('library/music/clips/humming.mp3')} volume={0.30} loop />
      {/* AUDIO POLICY — bare minimum guidance.
          One 15s session intro + one ~18s spoken intro at the head of each technique.
          The repeating inhale/exhale/hold/kumbhaka cue clips were removed: over a 5-minute
          hold they read as chatter rather than guidance. Pacing is carried visually by the
          CircularTimer dot and the BreathingPhasePanel countdown instead.
          Do not re-add per-cycle cue audio. */}
      {/* Each technique opens with its spoken instruction inside the lead-in window
          (PranayamSpec.leadInSec), so breathing never starts while the voice is talking. */}
      {isIntro && (
        <Sequence from={0} durationInFrames={INTRO_SEC * fps}>
          <Audio src={staticFile('library/audio/pranayam/intro_voice.mp3')} volume={0.85} />
        </Sequence>
      )}
      {isBhastrika && (
        <Sequence from={T_BHASTRIKA * fps} durationInFrames={VOICE_WINDOW_SEC * fps}>
          <Audio src={staticFile('library/audio/pranayam/bhastrika_voice.mp3')} volume={0.85} />
        </Sequence>
      )}
      {isKapalbhati && (
        <Sequence from={T_KAPALBHATI * fps} durationInFrames={VOICE_WINDOW_SEC * fps}>
          <Audio src={staticFile('library/audio/pranayam/kapalbhati_voice.mp3')} volume={0.85} />
        </Sequence>
      )}
      {isAnulomVilom && (
        <Sequence from={T_ANULOM * fps} durationInFrames={VOICE_WINDOW_SEC * fps}>
          <Audio src={staticFile('library/audio/pranayam/anulom_vilom_voice.mp3')} volume={0.85} />
        </Sequence>
      )}
      {isBahya && (
        <Sequence from={T_BAHYA * fps} durationInFrames={VOICE_WINDOW_SEC * fps}>
          <Audio src={staticFile('library/audio/pranayam/bahya_voice.mp3')} volume={0.85} />
        </Sequence>
      )}
      {isBhramari && (
        <Sequence from={T_BHRAMARI * fps} durationInFrames={VOICE_WINDOW_SEC * fps}>
          <Audio src={staticFile('library/audio/pranayam/bhramari_voice.mp3')} volume={0.85} />
        </Sequence>
      )}
      {/* --- BREATHING SOUND ---
          Not spoken cues (those were removed as chatter) but the sound of the practice
          itself, so the rhythm is followable with the eyes closed. One pre-rendered track
          per technique covers exactly one round; it is placed once per round at a start
          time derived from the spec, so retiming a technique retimes its audio.
          Each track's length equals roundSeconds() — see gen_pranayam_sfx.py. */}
      {isActiveTechnique && (() => {
        const spec = PRANAYAM_SPECS[currentType];
        const roundLen = roundSeconds(spec);
        const roundSlot = roundLen + spec.restBetweenRoundsSec;
        // Bhastrika breath sounds are louder/more forceful by nature — keep them subtle
        const breathVolume = currentType === 'bhastrika' ? 0.10 : 0.55;
        return Array.from({ length: spec.rounds }).map((_, r) => {
          const at = currentStartSec + spec.leadInSec + r * roundSlot;
          return (
            <Sequence
              key={`breath-${currentType}-${r}`}
              from={Math.round(at * fps)}
              durationInFrames={Math.round(roundLen * fps)}
              style={{
                translate: "1081px 664.4px"
              }}>
              <Audio src={staticFile(BREATH_TRACKS[currentType])} volume={breathVolume} />
            </Sequence>
          );
        });
      })()}
      {/* --- GENTLE PHASE CUE VOICES ---
          One soft spoken word at the START of each phase (Inhale → Hold → Exhale → Hold).
          No counting — the visual ring handles the timing. Kapalbhati is skipped because
          1-second strokes would turn every breath into a voice cue, which is noise.
          Anulom Vilom uses nostril-specific cues (inhale_left / exhale_right etc). */}
      {isActiveTechnique && currentType !== 'kapalbhati' && (() => {
        const spec = PRANAYAM_SPECS[currentType];
        const cycle = cycleSeconds(spec);
        const roundLen = roundSeconds(spec);
        const roundSlot = roundLen + spec.restBetweenRoundsSec;
        const CUE_VOL = 0.55;
        const cues: React.ReactNode[] = [];

        // Map each active phase to its cue file, respecting nostril for Anulom Vilom
        const phaseFile = (phase: 'inhale' | 'hold1' | 'exhale' | 'hold2', side: 'left' | 'right') => {
          if (phase === 'hold1') return 'library/audio/pranayam/cue_hold.mp3';
          if (phase === 'hold2') return 'library/audio/pranayam/cue_hold.mp3';
          if (spec.alternatesSides) {
            if (phase === 'inhale') return side === 'left' ? 'library/audio/pranayam/cue_inhale_left.mp3' : 'library/audio/pranayam/cue_inhale_right.mp3';
            if (phase === 'exhale') return side === 'left' ? 'library/audio/pranayam/cue_exhale_right.mp3' : 'library/audio/pranayam/cue_exhale_left.mp3';
          }
          if (phase === 'inhale') return 'library/audio/pranayam/cue_inhale.mp3';
          return 'library/audio/pranayam/cue_exhale.mp3';
        };

        for (let r = 0; r < spec.rounds; r++) {
          const roundStart = currentStartSec + spec.leadInSec + r * roundSlot;
          for (let b = 0; b < spec.breathsPerRound; b++) {
            const breathStart = roundStart + b * cycle;
            const side: 'left' | 'right' = b % 2 === 0 ? 'left' : 'right';
            const isFirstBreathOfRound = b === 0;

            // Fire cues at the start of each active phase
            let offset = 0;
            for (const phase of ['inhale', 'hold1', 'exhale', 'hold2'] as const) {
              const dur = spec.pattern[phase];
              if (dur > 0) {
                const at = breathStart + offset;
                const key = `cue-${currentType}-r${r}-b${b}-${phase}`;

                // Play gentle full affirmation ONCE on breath 1 of each round for inhale/exhale
                let soundFile = phaseFile(phase, side);
                let soundVol = 0.85;
                let soundDur = dur;

                if (isFirstBreathOfRound && (phase === 'inhale' || phase === 'exhale')) {
                  soundFile = phase === 'inhale'
                    ? 'library/audio/pranayam/affirmation_inhale.mp3'
                    : 'library/audio/pranayam/affirmation_exhale.mp3';
                  soundVol = 0.85;
                  soundDur = 4.5;
                }

                cues.push(
                  <Sequence
                    key={key}
                    from={Math.round(at * fps)}
                    durationInFrames={Math.round(soundDur * fps)}
                    style={{
                      translate: "187.1px 67.8px"
                    }}>
                    <Audio src={staticFile(soundFile)} volume={soundVol} />
                  </Sequence>
                );
                offset += dur;
              }
            }
          }
          // End-of-round closing retention cues: Inhale → Hold → Exhale → Rest
          if (spec.endOfRoundInhaleSec > 0) {
            const inhaleStart = roundStart + roundLen - spec.endOfRoundInhaleSec - spec.endOfRoundAntarSec - spec.endOfRoundBahyaSec;

            // "Inhale" — deep catch-up breath
            cues.push(
              <Sequence key={`cue-${currentType}-r${r}-roundinhale`} from={Math.round(inhaleStart * fps)} durationInFrames={Math.round(3 * fps)}>
                <Audio src={staticFile('library/audio/pranayam/cue_inhale.mp3')} volume={CUE_VOL} />
              </Sequence>
            );

            // "Hold" — antar kumbhaka
            if (spec.endOfRoundAntarSec > 0) {
              const antarStart = inhaleStart + spec.endOfRoundInhaleSec;
              cues.push(
                <Sequence key={`cue-${currentType}-r${r}-antar`} from={Math.round(antarStart * fps)} durationInFrames={Math.round(3 * fps)}>
                  <Audio src={staticFile('library/audio/pranayam/cue_hold.mp3')} volume={CUE_VOL} />
                </Sequence>
              );

              // "Exhale" — release the held breath, 0.5s before hold ends
              const exhaleStart = antarStart + spec.endOfRoundAntarSec - 0.5;
              cues.push(
                <Sequence key={`cue-${currentType}-r${r}-roundexhale`} from={Math.round(exhaleStart * fps)} durationInFrames={Math.round(3 * fps)}>
                  <Audio src={staticFile('library/audio/pranayam/cue_exhale.mp3')} volume={CUE_VOL} />
                </Sequence>
              );
            }
          }

          // "Rest" — at the start of the between-rounds rest (skip after the last round)
          if (r < spec.rounds - 1 && spec.restBetweenRoundsSec > 0) {
            const restStart = roundStart + roundLen; // exact frame when rest begins
            cues.push(
              <Sequence key={`cue-${currentType}-r${r}-rest`} from={Math.round(restStart * fps)} durationInFrames={Math.round(3 * fps)}>
                <Audio src={staticFile('library/audio/pranayam/cue_rest.mp3')} volume={CUE_VOL} />
              </Sequence>
            );
          }
        } // end for(r)
        return cues;
      })()}
      {/* Sparkle Particles */}
      <SparkleParticlesOverlay count={30} />
      {/* Botanical Leaf Flourish */}
      <svg width="220" height="140" viewBox="0 0 220 140" fill="none"
        style={{ position: 'absolute', top: 0, right: 0, opacity: 0.35, pointerEvents: 'none' }}>
        <path d="M220 0 Q140 30 100 120 M140 40 Q180 20 220 10 M120 70 Q160 50 200 40 M105 100 Q140 80 180 80" stroke="#cfa864" strokeWidth="1.5" />
        <circle cx="100" cy="120" r="4" fill="#cfa864" />
      </svg>
      {/* Top Header Bar */}
      <div style={{
        position: 'absolute', top: '24px', left: '48px', right: '48px',
        display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', zIndex: 50
      }}>
        <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'row', alignItems: 'center', gap: '18px' }}>
          <div style={{
            width: '58px', height: '58px', borderRadius: '14px', flexShrink: 0,
            backgroundColor: 'rgba(255,253,248,0.85)', border: '1.5px solid rgba(207,168,100,0.5)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            boxShadow: '0 6px 20px rgba(122,106,88,0.10)', overflow: 'hidden'
          }}>
            <Img
              src={staticFile('library/logos/si-logo.png')}
              style={{ width: '42px', height: '42px', objectFit: 'contain' }}
              from={736} />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <div style={{ fontFamily: FONT_DISPLAY, fontSize: '22px', fontWeight: 700, color: '#2b2520', letterSpacing: '0.04em', lineHeight: 1.1 }}>
              SOULFUL INTELLIGENCE STUDIO
            </div>
            <div style={{ fontFamily: FONT_BODY, fontSize: '12px', fontWeight: 800, color: '#7a6a58', letterSpacing: '0.18em', marginTop: '3px', textTransform: 'uppercase' }}>
              BREATHE • OBSERVE • TRANSFORM
            </div>
          </div>

          {/* Whole-session countdown, spanning the empty width of the header.
              Fades out under the periodic LIKE banner rather than being covered by it. */}
          {!isEndPromo && (
            <>
              <div style={{ width: '1px', height: '46px', backgroundColor: 'rgba(207,168,100,0.45)', marginLeft: '12px', opacity: 1 - bannerOpacity }} />
              <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: '7px', opacity: 1 - bannerOpacity }}>
                <div style={{ display: 'flex', flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', gap: '12px' }}>
                  <span style={{ fontFamily: FONT_BODY, fontSize: '11px', fontWeight: 800, color: '#7a6a58', letterSpacing: '0.18em' }}>
                    TOTAL PRACTICE LEFT
                  </span>
                  <span style={{ fontFamily: FONT_DISPLAY, fontSize: '26px', fontWeight: 700, color: '#2b2520', lineHeight: 1 }}>
                    {sessionTimeLeft}
                  </span>
                </div>
                <div style={{ width: '100%', height: '5px', backgroundColor: 'rgba(207,168,100,0.22)', borderRadius: '3px', overflow: 'hidden' }}>
                  <div style={{ height: '100%', width: `${sessionProgress * 100}%`, backgroundColor: '#cfa864', borderRadius: '3px' }} />
                </div>
              </div>
            </>
          )}
        </div>

        {/* The WhatsApp QR lives in the footer banner alongside the other two QR codes —
            up here it collided with the LIKE banner and the practice-left bar. */}
      </div>
      {/* Main Stage
          Vertical budget: header bar ends at y=82, GlobalWrapper's brand banner owns the
          bottom 110px (+6px frame border). Keeping the stage inside 96..126 means nothing
          in here can ever slide under the banner. Usable area: 1832 x 858. */}
      <div style={{
        position: 'absolute', top: '96px', bottom: '126px', left: '44px', right: '44px',
        display: 'flex', flexDirection: 'row', alignItems: 'stretch', justifyContent: 'center', zIndex: 40,
        overflow: 'hidden'
      }}>
        {/* SESSION OVERVIEW (INTRO) */}
        {isIntro && (
          <div style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <SessionOverviewCard />
          </div>
        )}

        {/* REST INTERVALS */}
        {isResting && (
          <div style={{ width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
            {isRest1 && <RestCard startSec={T_REST_1} durationInSeconds={REST_SEC} nextTechniqueTitle="Skull Shining Breath" />}
            {isRest2 && <RestCard startSec={T_REST_2} durationInSeconds={REST_SEC} nextTechniqueTitle="Alternate Nostril Breathing" />}
            {isRest3 && <RestCard startSec={T_REST_3} durationInSeconds={REST_SEC} nextTechniqueTitle="External Breath Retention" />}
            {isRest4 && <RestCard startSec={T_REST_4} durationInSeconds={REST_SEC} nextTechniqueTitle="Humming Bee Breath" />}
          </div>
        )}

        {/* ACTIVE TECHNIQUE: 3-column layout matching reference design */}
        {isActiveTechnique && (
          <div style={{ width: '100%', display: 'flex', flexDirection: 'row', alignItems: 'stretch', gap: '20px' }}>

            {/* === COLUMN 1: Left Technique Info Card (470 + 20 gap) === */}
            <div style={{ flex: '0 0 470px', minWidth: 0, display: 'flex' }}>
              {isBhastrika && (
                <PranayamCard number={1} title="BHASTRIKA PRANAYAMA" sanskritName="Bellows Breathing" durationMinutes={5}
                  instructions={["Sit comfortably with a straight spine.", "Deep inhale through the nose.", "Forceful exhale through the nose.", "Maintain a steady, rhythmic pace.", "End each round holding the breath in."]} />
              )}
              {isKapalbhati && (
                <PranayamCard number={2} title="KAPALBHATI PRANAYAMA" sanskritName="Skull Shining Breath" durationMinutes={5}
                  instructions={["Sit upright with spine straight and shoulders relaxed.", "Exhale forcefully contracting lower abdominal muscles.", "Allow inhalation to happen naturally and passively.", "Keep rhythm steady and comfortable.", "End each round holding the breath in."]} />
              )}
              {isAnulomVilom && (
                <PranayamCard number={3} title="ANULOM VILOM" sanskritName="Alternate Nostril Breathing" durationMinutes={5}
                  instructions={["Close right nostril, inhale through the left.", "Hold the breath in — antar kumbhaka.", "Close left nostril, exhale through the right.", "Hold the breath out — bahya kumbhaka.", "Repeat, now leading with the right nostril."]} />
              )}
              {isBahya && (
                <PranayamCard
                  number={4} title="BAHYA PRANAYAMA" sanskritName="External Breath Retention" durationMinutes={5}
                  instructions={[
                    "Deep inhale followed by complete exhalation.",
                    "Hold breath out and engage Root Lock (Mula Bandha).",
                    "Pull stomach in for Abdominal Lock (Uddiyana).",
                    "Touch chin to chest for Throat Lock (Jalandhara).",
                    "Release locks smoothly before inhaling."
                  ]}
                  illustrationImage="library/images/BandhasDiagram.png"
                  illustrationCaption="Maha Bandha: Throat, Abdominal & Root Locks"
                />
              )}
              {isBhramari && (
                <PranayamCard
                  number={5} title="BHRAMARI PRANAYAMA" sanskritName="Humming Bee Breath" durationMinutes={5}
                  instructions={[
                    "Thumbs on ears & fingers over eyes & lips (Shanmukhi Mudra).",
                    "Inhale deeply through your nose.",
                    "Pause briefly at the top of the inhale.",
                    "Exhale with a steady humming sound like a bee.",
                    "Feel the vibration resonate through your head."
                  ]}
                  illustrationImage="library/images/ShanmukhiMudra.png"
                  illustrationCaption="Shanmukhi Mudra Hand Position"
                />
              )}
            </div>

            {/* === COLUMN 2: Center — Unified Card (Badges + Circular Timer) + Next Card === */}
            <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', alignItems: 'stretch', gap: '12px' }}>

              {/* Single Unified Card containing STROKE, ROUND, and CIRCULAR TIMER */}
              <div style={{
                flex: 1, width: '100%', minHeight: 0,
                backgroundColor: 'rgba(255,253,248,0.85)',
                border: '1.5px solid rgba(207,168,100,0.40)',
                borderRadius: '28px',
                display: 'flex', flexDirection: 'column', alignItems: 'stretch',
                boxShadow: '0 16px 40px rgba(122,106,88,0.10)',
                backdropFilter: 'blur(24px)',
                overflow: 'hidden'
              }}>
                {/* Integrated Top Bar inside Card */}
                {breathState && (
                  <div style={{
                    display: 'flex', flexDirection: 'row', alignItems: 'center',
                    borderBottom: '1px solid rgba(207,168,100,0.25)',
                    backgroundColor: 'rgba(255,253,248,0.60)',
                    flexShrink: 0
                  }}>
                    {/* BREATH / STROKE / CYCLE */}
                    <div style={{ flex: 1, display: 'flex', flexDirection: 'row', alignItems: 'center', gap: '12px', padding: '14px 24px' }}>
                      <div style={{ fontSize: '20px' }}>🔄</div>
                      <div style={{ display: 'flex', flexDirection: 'column' }}>
                        <div style={{ fontFamily: FONT_BODY, fontSize: '10px', fontWeight: 800, color: COLORS.accent, letterSpacing: '0.18em', textTransform: 'uppercase' }}>
                          {PRANAYAM_SPECS[currentType].repUnit}
                        </div>
                        <div style={{ fontFamily: FONT_DISPLAY, fontSize: '26px', fontWeight: 700, color: '#2b2520', lineHeight: 1 }}>
                          {String(breathState.started && !breathState.resting ? breathState.repIndex : 0).padStart(2, '0')}
                          <span style={{ fontSize: '16px', fontWeight: 500, color: '#7a6a58', marginLeft: '5px' }}>
                            / {String(breathState.repsPerRound).padStart(2, '0')}
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Vertical divider */}
                    <div style={{ width: '1px', height: '36px', backgroundColor: 'rgba(207,168,100,0.30)' }} />

                    {/* ROUND */}
                    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '14px 24px', backgroundColor: `${COLORS.accent}12` }}>
                      <div style={{ fontFamily: FONT_BODY, fontSize: '10px', fontWeight: 800, color: COLORS.accent, letterSpacing: '0.20em', textTransform: 'uppercase' }}>ROUND</div>
                      <div style={{ fontFamily: FONT_DISPLAY, fontSize: '30px', fontWeight: 700, color: COLORS.accent, lineHeight: 1, marginTop: '2px' }}>
                        {breathState.round}
                        <span style={{ fontSize: '17px', fontWeight: 600, opacity: 0.75, marginLeft: '6px' }}>OF {breathState.rounds}</span>
                      </div>
                    </div>
                  </div>
                )}

                {/* Circular Timer filling remaining card space */}
                <div style={{ flex: 1, minHeight: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <CircularTimer startSec={currentStartSec} type={currentType} />
                </div>
              </div>

              {/* Dynamic Healing Breath Affirmations Card */}
              <div style={{ width: '100%', flexShrink: 0 }}>
                <BreathAffirmationCard startSec={currentStartSec} type={currentType} />
              </div>
            </div>

            {/* === COLUMN 3: Right — Breathing Phase Panel === */}
            <div style={{ flex: '0 0 400px', minWidth: 0, display: 'flex', flexDirection: 'column' }}>
              <BreathingPhasePanel startSec={currentStartSec} type={currentType} />
            </div>
          </div>
        )}
      </div>
    </AbsoluteFill>
  );
};

export default Daily5Pranayam;
