// GENERATED by gen_pranayam_voice.py — do not edit by hand.
// Spoken word timings from the TTS engine's own word-boundary events, so the
// intro card highlights each technique at the exact moment it is named.

export const INTRO_TECHNIQUE_MARKS: number[] = [12.98, 14.34, 16.17, 18.03, 20.03];

/** When "five minutes" is spoken, for the duration badges. */
export const INTRO_DURATION_MARK: number | null = 24.87;

/** How long each highlight stays lit. */
export const INTRO_HIGHLIGHT_SEC = 2.2;
