// GENERATED by gen_pranayam_voice.py — do not edit by hand.
// Spoken word timings from the TTS engine's own word-boundary events, so the
// intro card highlights each technique at the exact moment it is named.
// Each level has its own narration and therefore its own timings.

export interface IntroMarks {
  /** Second at which each technique name begins, in session order. */
  techniques: number[];
  /** When the practice length is spoken, for the duration badges. */
  duration: number | null;
}

export const INTRO_MARKS: Record<string, IntroMarks> = {
  beginner: { techniques: [12.98, 14.34, 16.17, 18.03, 20.03], duration: 24.87 },
  intermediate: { techniques: [18.16, 19.54, 21.39, 23.33, 25.34], duration: 30.21 },
};

/** How long each highlight stays lit. */
export const INTRO_HIGHLIGHT_SEC = 2.2;
